# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18ae2d7fa4831a6caf83ae4a47d9a534b8156a2f1070225ed5ccfd8f2610e046d28355cd12607e718478fe7c26d34c9a96ec8e64b2a2e86b2847d8adbcc24454

test:
  secret_key_base: b0d60a7af4e9c4c76aa68b017b25320d5a32cbbecec3c5e90a18cf288424811dc596caf65582822bca853b4b9e4bed859f9625d585b0028987487280378af51e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
